### ISSUE TITLE
Zoidberg setup

### ISSUE THREAD

**Issue by wojteeek** [kirkegaard/zoidberg.py#1]
Hi, 

It seems zoidberg's not using modern SlackClient - after updating imports to slack and replaced SlackClient with RTMClient, I managed it to run, but Sanic throws exception immediately after receiving webhook call from Slack ("404 for {} URL"). Any ideas where to start debugging?

**Comment by kirkegaard** [comment]
If i remember correctly, the sanic thing was me trying to support slacks slash commands. I think i moved that part to a different file but never got around to updating this repo. Let me check up on this tonight :)

**Comment by kirkegaard** [comment]
There we go :) No more sanic!

**Comment by kirkegaard** [comment]
@wojteeek I've added support for slacks new api :)
